apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-managed-stack
  namespace: kargo-managed-stack
spec:
  promotionPolicies:
    - stageSelector:
        name: devpreview
      autoPromotionEnabled: true
    - stageSelector:
        name: dev2preview
      autoPromotionEnabled: true
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
    - stageSelector:
        name: dev2
      autoPromotionEnabled: true
    - stageSelector:
        name: qapreview
      autoPromotionEnabled: true
